spring:
  application:
    name: community
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB

mybatis:
  configuration:
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.ls.community.model

#logging:
#  level:
#    com.ls.community.mapper: DEBUG

qiniuyun:
  accessKey: _3PM93n1Hw69y92DsL7lXkINPO6itnGq68Ka1Qy9
  secretKey: cz6jsXegkIoIR_9DwpWl8IMuRA3qppYN4adhGPAs
  bucket: community-storage
  domain: http://re2uz7udr.hd-bkt.clouddn.com/
