server:
  port: 8887

github:
  client:
    id: Iv1.0a2d489403875473
    secret: a5d557cd9dd15010f8e6a4fe9abb1474189b6770
  redirect-uri: http://localhost:8887/callback
spring:
  datasource:
    url: jdbc:h2:~/community
    username: root
    password: root
    driver-class-name: org.h2.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.ls.community.model

qiniuyun:
  accessKey: _3PM93n1Hw69y92DsL7lXkINPO6itnGq68Ka1Qy9
  secretKey: cz6jsXegkIoIR_9DwpWl8IMuRA3qppYN4adhGPAs
  bucket: community-storage
  domain: http://re2uz7udr.hd-bkt.clouddn.com/
