server:
  port: 8887

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/community
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

logging:
  file:
    path: C:/ls/java/javaIO/logs
  level:
    root: debug
    com.ls.community: debug

file:
  staticAccessPath: /files/**
  uploadFolder: C:/ls/java/javaIO/uploadFiles

github:
  client:
    id: Iv1.0a2d489403875473
    secret: a5d557cd9dd15010f8e6a4fe9abb1474189b6770
  redirect-uri: http://localhost:8887/callback/github

gitee:
  client:
    id: 4dbb7b7dce4eadfbfd98f958d6530fb800c56c4d81a7133b1fdd1889ee435ef6
    secret: 20c69206986b36db59e2043a8846c1f7f403d0dbb37605b0bc1de6292cdacb13
  redirect-uri: http://localhost:8887/callback/gitee

